# Matrizes

In [ ]:
import numpy as np #muito usada para processamento científico e estatística (muito usada em IA) - leia-se "numpai"

In [ ]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]]) #matrix 2X3 (duas linhas e 3 colunas)

In [ ]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [ ]:
matriz.shape #formato (2x3, neste caso)

(2, 3)

In [ ]:
matriz[0] #primeira linha

array([2, 3, 1])

In [ ]:
matriz[1] #segunda linha

In [ ]:
matriz[0][2] #elemento sempre [linha][coluna]

1

In [ ]:
matriz[1][2]

7

In [ ]:
matriz.shape

(2, 3)

In [ ]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])  

[2 3 1]
2
3
1
[4 5 7]
4
5
7


# **Exercícios de fixação**


1. Lista: Crie uma estrutura de repetição para fazer a leitura de 5 números inteiros e os armazene dentro de uma lista. Após a leitura, crie outra estrutura de repetição para somar todos os valores digitados



2. Dicionário: Crie um dicionário para armazenar o nome e a nota de 3 alunos, fazendo a leitura dos valores por meio de uma estrutura de repetição. Depois, crie uma nova estrutura de repetição para somar todas as notas e retornar a média



3. Matriz: Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz

matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])


Resolução 1:

In [ ]:
lista = []
for _ in range(1, 6):
  valor = int(input('Digite o valor: '))
  lista.append(valor)

Digite o valor: 10
Digite o valor: 10
Digite o valor: 10
Digite o valor: 10
Digite o valor: 10


In [ ]:
lista

[10, 10, 10, 10, 10]

In [ ]:
len(lista)

5

In [ ]:
soma = 0
for i in range(len(lista)):
  #print(lista[i])
  soma += lista[i]
print('Soma: ', soma)

Soma:  50


In [ ]:
#outra forma de fazer
import numpy as np
np.array(lista).sum()

50

Resolução 2:

In [ ]:
alunos = {}
for _ in range(1, 4):
  nome = input('Digite o nome: ')
  nota = float(input('Digite a nota: '))
  alunos[nome] = nota 

Digite o nome: Thiago
Digite a nota: 10
Digite o nome: João
Digite a nota: 8
Digite o nome: Bla
Digite a nota: 2


In [ ]:
alunos

{'Bla': 2.0, 'João': 8.0, 'Thiago': 10.0}

In [ ]:
alunos['Thiago']

10.0

In [ ]:
alunos.values()

dict_values([10.0, 8.0, 2.0])

In [ ]:
soma = 0
for nota in alunos.values():
  #print(nota)
  soma += nota
print('Média: ', soma / 3)

Média:  6.666666666666667


Resolução - Ex 3

In [ ]:
matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])
matriz

array([[3, 4, 1],
       [3, 1, 5]])

In [ ]:
matriz.shape

(2, 3)

In [31]:
soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    #print(matriz[i][j])
    soma += matriz[i][j]
print('Soma: ', soma)

Soma:  17
